server:
  port: 9080

logging:
  path: logs
  file: daine.log
spring:
  application:
    name: daine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:/test?serverTimezone=GMT
    username: 
    password: 

mybatis:
  mapper-locations:
    - mapper/*
  type-aliases-package: com.course.model

